from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch
from datetime import datetime

styles = getSampleStyleSheet()

title_style = styles["Title"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#1E3A8A")

heading_style = styles["Heading2"]
heading_style.textColor = HexColor("#1565C0")

normal_style = styles["BodyText"]


def generate_pdf(result, score, skill_match):

    filename = "Resume_Analysis_Report.pdf"

    doc = SimpleDocTemplate(
        filename,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    story = []

    # ===========================
    # Title
    # ===========================

    story.append(
        Paragraph(
            "AI Resume Analysis Report",
            title_style
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # ===========================
    # Job Fit
    # ===========================

    if score >= 80:
        job_fit = "Excellent"

    elif score >= 60:
        job_fit = "Good"

    elif score >= 40:
        job_fit = "Average"

    else:
        job_fit = "Poor"

    # ===========================
    # Summary Table
    # ===========================

    table_data = [
        ["ATS Score", f"{score}/100"],
        ["Skill Match", f"{skill_match}%"],
        ["Job Fit", job_fit],
        ["Generated On", datetime.now().strftime("%d-%m-%Y %H:%M")]
    ]

    table = Table(table_data, colWidths=[2.5 * inch, 3 * inch])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#E3F2FD")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # ===========================
    # Professional Summary
    # ===========================

    story.append(
        Paragraph(
            "Professional Summary",
            heading_style
        )
    )

    story.append(
        Paragraph(
            result["professional_summary"],
            normal_style
        )
    )

    story.append(Spacer(1, 15))

    # ===========================
    # Helper Function
    # ===========================

    def add_section(title, items):

        story.append(
            Paragraph(
                title,
                heading_style
            )
        )

        if items:

            for item in items:

                story.append(
                    Paragraph(
                        f"• {item}",
                        normal_style
                    )
                )

        else:

            story.append(
                Paragraph(
                    "None",
                    normal_style
                )
            )

        story.append(Spacer(1, 15))

    # ===========================
    # Sections
    # ===========================

    add_section("Matching Skills", result["matching_skills"])
    add_section("Missing Skills", result["missing_skills"])
    add_section("Strengths", result["strengths"])
    add_section("Weaknesses", result["weaknesses"])
    add_section("Suggestions", result["suggestions"])

    # ===========================
    # Footer
    # ===========================

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Generated by AI Resume Analyzer</b>",
            heading_style
        )
    )

    story.append(
        Paragraph(
            "Developed by Ragul M",
            normal_style
        )
    )

    doc.build(story)

    return filename